spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adocao_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    enabled: true
#    url: jdbc:postgresql://localhost:5432/adocao_db
#    user: admin
#    password: admin